### ISSUE TITLE
白線認識

### ISSUE THREAD

**Issue by yuzukiimai** [rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo#10]

**Comment by yuzukiimai** [comment]
## 白線認識し, 然るべき位置で停止する機能の追加を行う

1. YOLOで白線を認識できるようにする
2. ROS 2のノードとして実装する
3. Navigation2とserviceを用いてモードや速度の切り替えなどを実装する
4. 津田沼キャンパスで実機で試す

### 1
- [x] YOLOの環境構築
- [x] データセット集め
- [x] 学習をさせる
- [x] ある程度, 白線を認識できる

### 2
- [x] ROS 2のノード化

### 3
- [ ] waypointから白線認識モードに変更するserviceを飛ばせるようにする
- [ ] 白線認識モード用の速度に切り替えるようにする
- [ ] 停止してから再開する際に, 白線認識モードから抜けるようにする

### 4
- [ ] 実機で成功
- [ ] 複数の照度条件でも成功

**Comment by masakifujiwara1** [comment]
今年は，waypointで停止を行う．
