### ISSUE TITLE
3D-LiDAR

### ISSUE THREAD

**Issue by Ryusei-Baba** [rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo#14]
## R-fansをつくばチャレンジ2023で使用する
- [x] ROS 1での動作確認
- [x] ros1_bridgeの調査
- [x] ROS 1とROS 2の両方使用できる環境を整える
- [x] ros1_bridgeを用いて実装
- [x] 可能であればROS 2移行

**Comment by haruyama8940** [comment]
つくばチャレンジの１回目の自律走行で，brigeを挟むと起動が複雑になると体感
ドライバーのros2が急務
7月中をめどに作業する

**Comment by haruyama8940** [comment]
動画は後ほど添付するが
rfansからパケットを受け取るところまでROS 2化確認

作業中のリポジトリ
https://github.com/haruyama8940/rfans_driver_ros2.git

なおノーライセンスのリポジトリであり，権利関係が怪しいため，完成次第プライベートリポジトリにします

**Comment by haruyama8940** [comment]
下記の動画でしめすようにROS2上でRfansを動作させることに成功．
コードがとっ散らかっているため，リファクタリングします
https://youtu.be/C7FVlmA4FzU

**Comment by haruyama8940** [comment]
リファクタリングしました
またorne_boxのリポジトリにlaunchファイルを追加しました
