### ISSUE TITLE
IMUがゾンビになる問題

### ISSUE THREAD

**Issue by haruyama8940** [rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo#21]
ADIS16465を用いている
https://github.com/uhobeike/adi_driver2
ではcontrol +cなどでNodeを終了した場合にゾンビプロセスになることがある．
適切に終了するように改良する

**Comment by masakifujiwara1** [comment]
ros2において, `ps aux | grep adi_driver `をした際に表示されたプロセスの全てを`kill -9 `コマンドを使用して終了させた. その後, 再度adi_driver2を起動させたが接続に失敗した.

**Comment by masakifujiwara1** [comment]
取り敢えず, 使用するだけならUSBを抜き差しすることで, 再度使用可能になることを確認
