### ISSUE TITLE
VNC接続問題

### ISSUE THREAD

**Issue by masakifujiwara1** [rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo#24]

**Comment by yuzukiimai** [comment]
・前回の接続先での接続がうまくいかない場合, その接続先を消し, 左上のFileの欄からNew connectionを選択して再度つなぎ直すと確実に1回で接続できることを確認した.

VNC Server :「ornebox3-jetson」
password :「orne」


・尚, 相変わらずubuntu同士での接続はできないよう...
