### ISSUE TITLE
jetsonが再起動する原因の調査

### ISSUE THREAD

**Issue by masakifujiwara1** [rdc-autonomous-mobile-robot-project/tsukuba2023_ToDo#34]
#33 で問題となったjetsonが勝手に再起動する問題について，調査を行う．

**Comment by haruyama8940** [comment]
jetson power GUIによるデバッグでは原因の特定には至ってない．
前回の実験走行（11/3,11/4）で鉛蓄電池を交換したところ，今のところは再起動に直面していない
